use_frameworks!

platform :ios, '8.0'

target 'StaticFrameworkTest_Example' do
  pod 'StaticFrameworkTest', :path => '../'

  target 'StaticFrameworkTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
